# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - witsecurevirusscanner

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_da3cdcef4b084245a1f23db94610ec39 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2f2b59380c3c4ae9892140feee224a20 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_da3cdcef4b084245a1f23db94610ec39 }}/withsecure-interview-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'witsecurevirusscanner'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_199ef1284ed04a359fdfffa86f28b3b8 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_da3cdcef4b084245a1f23db94610ec39 }}/withsecure-interview-api:${{ github.sha }}'